name: Deploy MES Application

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
    - name: Set environment variables
      id: set-vars
      run: |
        if [ "${{ env.BRANCH_NAME }}" = "main" ]; then
          echo "SSH_HOST=${{ secrets.SSH_HOST_AXXONET_MAIN }}" >> $GITHUB_ENV
          echo "SSH_USER=${{ secrets.SSH_USERNAME_AXXONET_MAIN }}" >> $GITHUB_ENV
          echo "DEPLOY_PATH=/home/ubuntu/test" >> $GITHUB_ENV
          echo "SSH_KEY_SECRET=SSH_PRIVATE_KEY_AXXONET_MAIN" >> $GITHUB_ENV
        elif [ "${{ env.BRANCH_NAME }}" = "dev" ]; then
          echo "SSH_HOST=${{ secrets.SSH_HOST_AXXONET_DEV }}" >> $GITHUB_ENV
          echo "SSH_USER=${{ secrets.SSH_USERNAME_AXXONET_DEV }}" >> $GITHUB_ENV
          echo "DEPLOY_PATH=/home/axxonet/test" >> $GITHUB_ENV
          echo "SSH_KEY_SECRET=SSH_PRIVATE_KEY_AXXONET_DEV" >> $GITHUB_ENV
        fi

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets[env.SSH_KEY_SECRET] }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh ${SSH_USER}@${SSH_HOST} << EOF
          cd ${DEPLOY_PATH}
          git pull origin ${BRANCH_NAME}
          cat README.md
        EOF
