name: Deploy MES Application

on:
  push:
    branches:
      - main

jobs:
  deploy-main-to-axxonet:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_AXXONET }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST_AXXONET }} >> ~/.ssh/known_hosts

    - name: Deploy on AXXONET Server
      run: |
        ssh ${{ secrets.SSH_USERNAME_AXXONET }}@${{ secrets.SSH_HOST_AXXONET }} << EOF
          cd /home/axxonet/test/
          git pull origin main
          cat README.md
        EOF
